version: '3'
services:
  postgres:
    image: postgres:15-bullseye
    hostname: postgres
    restart: always
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  spring-app:
    build : .
    ports:
      - "8080:8080"
    environment:
      spring.datasource.url: "jdbc:postgresql://postgres:5432/test"
    depends_on:
      - postgres
